title: Anhar Tasman
subtitle: Just a man and his will to survive
description: >- # this means to ignore newlines until "baseurl:"
  learn and share

url: "" # the base hostname & protocol for your site, e.g. https://example.github.io
baseurl: "" # the subpath of your site, e.g. /blog

# Navigation
urls:
    - text: Home
      url: /
    - text: About
      url: /about
    - text: Blog
      url: /blog
    - text: Gallery
      url: /gallery
    # - text: Shop
    #   url : /shop
    - text: Contact
      url : /contact


# Edit Author details (For multi authors check _data/authors.yml)

author_logo: authors/anhartasman.png
author: Anhar Tasman
author_bio: With over 5 years of experience in programming, I have successfully developed mobile and web applications for a variety of clients. In my most recent role as Senior Programmer, I have consistently delivered high-quality work, resulting in a 20% increase in client satisfaction within 6 months. Available for new projects in 2 weeks.
author_email: "tasmananhar@gmail.com"
author_location: Indonesia
author_website_url:
typewrite-text: everyday above the ground is a blessing
hero_cover_img: sample_cover.jpg # replace this for changing homepage cover (eg. try cover.jpeg). Image should be in /assets/img

# Experiences
author_work_experiences:
            - company_name: ATA Corp
              work_date_range: Jakarta • 08/2016 - 04/2021
              company_logo: work/atacorp.jpeg
              company_url: https://grass.atacorp.co
              designation: Programmer
              description: Worked on mobile and web applications
              visibility: true

# Education
author_education_details:
              - college_logo: education/gunadarma.jpg
                edu_date_range: 09/2012 - 10/2016
                college_name: Gunadarma Univercity
                college_url: https://www.gunadarma.ac.id/
                college_degree: CS Engineer
                description: Bachelor of Technology
                visibility: true

# Projects
author_project_details:
              - project_thumbnail: portfolio/bkp/images/feat_image_bkp_supplier.png
                project_title: PASTANI Supplier
                project_info: Android
                project_description: Platform for farmers to sell their products
                project_url: https://play.google.com/store/apps/details?id=com.bkp.sislog_supplier
                visibility: true
              - project_thumbnail: portfolio/bkp/images/feat_image_bkp_grosir.jpg
                project_title: PASTANI Grosir
                project_info: Android
                project_description: To buy products from farmers
                project_url: https://play.google.com/store/apps/details?id=com.bkp.pastani
                visibility: true
              - project_thumbnail: portfolio/jagodompet/images/feat_image_jagodompet.png
                project_title: Jago Dompet
                project_info: Android
                project_description: Application for your expense history
                project_url: https://play.google.com/store/apps/details?id=com.gepreksoft.jagodompet
                visibility: true
              - project_thumbnail: portfolio/pikpakMobile/feat_image_pikpak.jpg
                project_title: Pikpak Mobile
                project_info: Android
                project_description: Ecommerce Application
                project_url: https://play.google.com/store/apps/details?id=com.alterindonesia.pikpak
                visibility: true
              - project_thumbnail: portfolio/klinops/feat_image_klinops.png
                project_title: Klinops
                project_info: Android
                project_description: Clinic Application For Clinic Owner
                project_url: https://play.google.com/store/apps/details?id=com.klinops.ops
                visibility: true
              - project_thumbnail: portfolio/klinops/feat_image_terops.png
                project_title: Klinops Personal
                project_info: Android
                project_description: Clinic Application For Terapist
                project_url: https://play.google.com/store/apps/details?id=com.klinops.personal
                visibility: true
              - project_thumbnail: portfolio/sabico/feat_image_sabico.png
                project_title: SABICO
                project_info: Android
                project_description: Bullying Report Application
                project_url: https://anhartasman.github.io/blog/portfolio-sabico
                visibility: true

# Certificates
author_certificate_details:
              - certificate_thumbnail: certificates/AnharSertifikatlombamembuatgame.jpg
                certificate_title: KOMPRES 2015/2016
                certificate_publisher: University Of Gunadarma
                certificate_date: 7 Jan 2016
                certificate_number: 
                visibility: true
              - certificate_thumbnail: certificates/AnharSertifikatDatabaseFundamental.png
                certificate_title: Microsoft Database Fundamental
                certificate_publisher: Microsoft
                certificate_date: 30 Jun 2015
                certificate_number: F365-7994
                visibility: true
              - certificate_thumbnail: certificates/AnharSertifikatHTML5.jpg
                certificate_title: Building Mobile Web With HTML 5
                certificate_publisher: University Of Gunadarma
                certificate_date: 13 Nov 2012
                certificate_number: 
                visibility: true
              - certificate_thumbnail: certificates/AnharSertifikatUbuntu.jpg
                certificate_title: Ubuntu Training
                certificate_publisher: Sekolah Tinggi Ilmu Komputer Cipta Karya Informatika
                certificate_date: 25 Feb 2012
                certificate_number: 1552/CKI/C/II/2012
                visibility: true
              - certificate_thumbnail: certificates/AnharSertifikatKompetensiKeahlian.jpg
                certificate_title: CERTIFICATE OF COMPETENCY
                certificate_publisher: PT. Bukaka Teknik Utama TbkPT. Bukaka Teknik Utama Tbk 
                certificate_date: 10 Mar 2011
                certificate_number: 022/BTU/SERT-UK/III/2011
                visibility: true

# social links
twitter_username: Anhar_Tasman
github_username:  anhartasman
facebook_username: anhar.tasman
linkedin_username: anhar-tasman-660ab156
behance_username:
instagram_username: anhartasman
medium_username:
telegram_username:
dribbble_username:
flickr_username:

#for comments ( we got Disqus and Hyvor Commenting, uncomment the one you want to use )

disqus_shortname: anhargithub
# hyvor_talk_website_id: 476

# wakatime username (coding activity)
wakatime_username: anhartasman

# mailchimp embedded form url (newsletter):
mailchimp_form_url: https://sujaykundu.us10.list-manage.com/subscribe/post?u=50bab1c85eae24ecfb0f68361&amp;id=3a2dd721d0

# contact form - (choose formspress or getform)
# getform_endpoint: 83b703c3-9e47-4df4-ac55-e24d7eb02abc
formspree_email: anhar_tasman@yahoo.com

# releases - widget can be (sidebar, modal or embed)
olvy_organization: devlopr
olvy_widget_type: sidebar

# syntax highlighter
markdown: kramdown
highlighter: rouge
permalink: pretty

# Choose what to show ( can be true or false)
show_author_work_experiences: true
show_author_education_details: true
show_author_project_details: true
show_author_certificate_details: true

# pagination of posts
paginate: 4
per_page: 4
paginate_path: "/blog/page/:num/"

# minify
# compress_html:
#   clippings: all
#   comments: ["<!-- ", " -->"]
#   endings: all
#   ignore:
#     envs: ['development']

# Archives
# jekyll-archives:
#   enabled:
#     - categories
#   layout: archive
#   permalinks:
#     category: '/category/:name/'

collections:
  products:
    output: true
  authors:
    output: true

defaults:
  -
    scope:
      path: "gallery"
    values:
      permalink: /:path/:basename:output_ext
  -
    scope:
      path: ""
      type: authors
    values:
      layout: author
      permalink: /blog/authors/:slug
  -
    scope:
      path: 'assets/**'
    values:
      sitemap: false

# Build settings
plugins:
  - jekyll-paginate
  - jekyll-gist
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-admin

# Jekyll Admin Config
jekyll_admin:
  # hidden_links:
  #   - posts
  #   - pages
  #   - staticfiles
  #   - datafiles
  #   - configuration
  homepage: "posts"


# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.

### Switching Deployment Strategy (in DEPLOY_STRATEGY) file change the key accordingly:
# none - For no default
# gh-pages - For Github Pages
# firebase - For Firebase Hosting

exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - assets/bower_components/isotope-layout/README.md
  - assets/bower_components/icono/README.md
  - assets/bower_components/font-awesome/advanced-options/use-with-node-js/fontawesome-svg-core/README.md
  - assets/bower_components/ghosthunter/README.md
  - assets/bower_components/nanobar/README.md
  - assets/bower_components/lightgallery/demo/README.md
  - assets/bower_components/font-awesome/advanced-options/use-with-node-js/free-brands-svg-icons/README.md
  - assets/bower_components/font-awesome/advanced-options/use-with-node-js/free-solid-svg-icons/README.md
  - assets/bower_components/jquery-mousewheel/README.md
  - assets/bower_components/get-size/README.md
  - assets/bower_components/font-awesome/advanced-options/use-with-node-js/fontawesome/README.md
  - assets/bower_components/jquery-mousewheel/ChangeLog/README.md
  - assets/bower_components/font-awesome/advanced-options/use-with-node-js/fontawesome-free-regular/README.md
  - assets/bower_components/desandro-matches-selector/README.md
  - assets/bower_components/ev-emitter/README.md
  - assets/bower_components/font-awesome/README.md
  - assets/bower_components/font-awesome/advanced-options/use-with-node-js/fontawesome-free-solid/README.md
  - assets/bower_components/font-awesome/advanced-options/use-with-node-js/fontawesome-free/README.md
  - assets/bower_components/font-awesome/advanced-options/use-with-node-js/fontawesome-free-webfonts/README.md
  - assets/bower_components/font-awesome/advanced-options/use-with-node-js/fontawesome-free-brands/README.md
  - assets/bower_components/font-awesome/advanced-options/use-with-node-js/fontawesome-common-types/README.md
  - assets/bower_components/ghosthunter/example/Index.html
  - assets/bower_components/lightgallery/test/lightgallery.html
  - assets/bower_components/masonry-layout/README.md
  - assets/bower_components/imagesloaded/README.md


destination: ./build
