# Site
name: "Anhar Tasman On Github"
description: "My adventure in coding world"
meta_description: "programmer indonesia, anak IT"
logo: 'assets/images/logo.png'
favicon: 'assets/images/logo.png'
baseurl:
google_analytics: 'UA-46278016-1'
disqus: 'anhartasman'
mailchimp-list: 'https://wowthemes.us11.list-manage.com/subscribe/post?u=8aeb20a530e124561927d3bd8&amp;id=8c3d2d214b'

# Authors
authors:
  anhartasman:
    name: Anhar Tasman
    display_name: Anhar Tasman
    gravatar: 888d75c8090bf12a5fc2b57f2082abf9
    email: anhar_tasman@yahoo.com
    web: https://anhartasman.github.io/
    twitter: https://twitter.com/Anhar_Tasman
    description: "Author of this blog"
  sal:
    name: Anhar Tasman
    display_name: Anhar Tasman
    gravatar: e56154546cf4be74e393c62d1ae9f9d4
    email: anhar_tasman@yahoo.com
    web: https://anhartasman.github.io/
    twitter: https://twitter.com/Anhar_Tasman
    description: "Author of this blog"
  john:
    name: John
    display_name: John
    gravatar: b1cc14991db7a456fcd761680bbc8f81
    email: wowthemesnet@gmail.com
    web: https://www.wowthemes.net
    twitter: https://twitter.com/wowthemesnet
    description: "This is the author box. Write a short description of the author here. You are currently previewing Mediumish demo, a Jekyll template compatible with Github pages."

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-archives

# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'

# Pagination
paginate: 6
paginate_path: /page:num/

# Other
markdown: kramdown
highlighter: rouge
